stages:
  - build
  - analyses_QA_rapport_tests
  - deploy-env-test
  - performance-test
  - deploy-env-prod

variables:
  SONAR_URL: "http://192.168.56.121:9000"
  SONAR_PROJECT_KEY: "Petclinic-SpringBoot"
  APP_JAR: "spring-petclinic-3.0.0-SNAPSHOT.jar"

# Cache pour accélérer les builds suivants
cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository
    - target/

before_script:
  - sudo apt update -y
  - sudo apt install -y openssh-client

build:
  stage: build
  script:
    - mvn package
  artifacts:
    paths:
      - $APP_JAR
    expire_in: 1 week
  # Exécuter seulement si des fichiers Java ou pom.xml sont modifiés
  rules:
    - changes:
        - "**/*.java"
        - "**/pom.xml"
      when: always

quality-analysis:
  stage: analyses_QA_rapport_tests
  script:
    - mvn sonar:sonar
      -Dsonar.projectKey=$SONAR_PROJECT_KEY
      -Dsonar.projectName='Petclinic-SpringBoot'
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.login=$SONAR_TOKEN

test-reports:
  stage: analyses_QA_rapport_tests
  script:
    - mvn test
  artifacts:
    reports:
      junit: "**/target/surefire-reports/TEST-*.xml"

deploy-test:
  stage: deploy-env-test
  script:
    - echo $SSH_PASS - $APP_JAR
    - sshpass -p "$SSH_PASS" scp -v -o StrictHostKeyChecking=no target/$APP_JAR vagrant@192.168.56.122:/tmp/
    - sshpass -p "$SSH_PASS" ssh -v -o StrictHostKeyChecking=no vagrant@192.168.56.122 "nohup java -jar /tmp/$APP_JAR > /dev/null 2>&1 &"
    - sleep 20
  environment:
    name: test
    url: http://192.168.56.122:8080
  
performance-test:
  stage: performance-test
  script:
    - sshpass -p "$SSH_PASS" scp -o StrictHostKeyChecking=no petclinic_test_plan.jmx vagrant@192.168.56.122:/tmp/
    - sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no vagrant@192.168.56.122 "/opt/jmeter/bin/jmeter -j jmeter.save.saveservice.output_format=xml -n -t /tmp/petclinic_test_plan.jmx -l /tmp/petclinic_test_plan.jtl"
    - sshpass -p "$SSH_PASS" scp -o StrictHostKeyChecking=no vagrant@192.168.56.122:/tmp/petclinic_test_plan.jtl .
  artifacts:
    paths:
      - petclinic_test_plan.jtl
    reports:
      junit: "petclinic_test_plan.jtl"
  
deploy-prod:
  stage: deploy-env-prod
  when: manual
  script:
    - sshpass -p "$SSH_PASS" scp -o StrictHostKeyChecking=no target/$APP_JAR vagrant@192.168.56.123:/tmp/
    - sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no vagrant@192.168.56.123 "nohup java -jar /tmp/$APP_JAR > /dev/null 2>&1 &"
  environment:
    name: production
    url: http://192.168.56.123:8080

